// Gematria — equivalent-words corpus and lookup. Ported verbatim.

export const EQUIVALENT_CORPUS = [
  /* ---------- HEBREW (Mispar Hechrechi) ---------- */
  { lang:'hebrew', word:'אהבה', translit:'ahava',     gloss:'love',                value:13 },
  { lang:'hebrew', word:'אחד',  translit:'echad',     gloss:'one · unity',         value:13 },
  { lang:'hebrew', word:'אהיה', translit:'ehyeh',     gloss:'I AM (divine name)',  value:21 },
  { lang:'hebrew', word:'יהוה', translit:'YHVH',      gloss:'the Tetragrammaton',  value:26 },
  { lang:'hebrew', word:'אל',   translit:'El',        gloss:'God (name)',          value:31 },
  { lang:'hebrew', word:'יהי',  translit:'yehi',      gloss:'let there be',        value:25 },
  { lang:'hebrew', word:'לב',   translit:'lev',       gloss:'heart',               value:32 },
  { lang:'hebrew', word:'כבוד', translit:'kavod',     gloss:'glory · honour',      value:32 },
  { lang:'hebrew', word:'אלהים',translit:'Elohim',    gloss:'God',                 value:86 },
  { lang:'hebrew', word:'הטבע', translit:'ha-teva',   gloss:'nature (= Elohim)',   value:86 },
  { lang:'hebrew', word:'אדני', translit:'Adonai',    gloss:'Lord',                value:65 },
  { lang:'hebrew', word:'היכל', translit:'heichal',   gloss:'palace · temple',     value:65 },
  { lang:'hebrew', word:'חי',   translit:'chai',      gloss:'alive',               value:18 },
  { lang:'hebrew', word:'חיים', translit:'chayim',    gloss:'life',                value:68 },
  { lang:'hebrew', word:'חכמה', translit:'chochmah',  gloss:'wisdom',              value:73 },
  { lang:'hebrew', word:'בינה', translit:'binah',     gloss:'understanding',       value:67 },
  { lang:'hebrew', word:'דעת',  translit:'daat',      gloss:'knowledge',           value:474 },
  { lang:'hebrew', word:'חסד',  translit:'chesed',    gloss:'lovingkindness',      value:72 },
  { lang:'hebrew', word:'גבורה',translit:'gevurah',   gloss:'strength',            value:216 },
  { lang:'hebrew', word:'תפארת',translit:'tiferet',   gloss:'beauty',              value:1081 },
  { lang:'hebrew', word:'נצח',  translit:'netzach',   gloss:'eternity · victory',  value:148 },
  { lang:'hebrew', word:'הוד',  translit:'hod',       gloss:'splendour',           value:15 },
  { lang:'hebrew', word:'יסוד', translit:'yesod',     gloss:'foundation',          value:80 },
  { lang:'hebrew', word:'מלכות',translit:'malkhut',   gloss:'kingdom',             value:496 },
  { lang:'hebrew', word:'כתר',  translit:'keter',     gloss:'crown',               value:620 },
  { lang:'hebrew', word:'שכינה',translit:'Shekhinah', gloss:'divine presence',     value:385 },
  { lang:'hebrew', word:'שלום', translit:'shalom',    gloss:'peace',               value:376 },
  { lang:'hebrew', word:'משיח', translit:'mashiach',  gloss:'messiah',             value:358 },
  { lang:'hebrew', word:'נחש',  translit:'nachash',   gloss:'serpent (= mashiach)',value:358 },
  { lang:'hebrew', word:'שטן',  translit:'satan',     gloss:'adversary',           value:359 },
  { lang:'hebrew', word:'מטטרון',translit:'Metatron', gloss:'archangel',           value:314 },
  { lang:'hebrew', word:'שדי',  translit:'Shaddai',   gloss:'Almighty',            value:314 },
  { lang:'hebrew', word:'מלאך', translit:'malach',    gloss:'angel · messenger',   value:91 },
  { lang:'hebrew', word:'אמן',  translit:'amen',      gloss:'amen (= malach)',     value:91 },
  { lang:'hebrew', word:'רוח',  translit:'ruach',     gloss:'spirit · wind',       value:214 },
  { lang:'hebrew', word:'נפש',  translit:'nefesh',    gloss:'soul · life-force',   value:430 },
  { lang:'hebrew', word:'נשמה', translit:'neshamah',  gloss:'breath · higher soul',value:395 },
  { lang:'hebrew', word:'אור',  translit:'or',        gloss:'light',               value:207 },
  { lang:'hebrew', word:'רז',   translit:'raz',       gloss:'secret (= or)',       value:207 },
  { lang:'hebrew', word:'תורה', translit:'Torah',     gloss:'Torah · teaching',    value:611 },
  { lang:'hebrew', word:'ישראל',translit:'Yisrael',   gloss:'Israel',              value:541 },
  { lang:'hebrew', word:'ירושלים',translit:'Yerushalayim',gloss:'Jerusalem',       value:596 },
  { lang:'hebrew', word:'ציון', translit:'Tzion',     gloss:'Zion',                value:156 },
  { lang:'hebrew', word:'יוסף', translit:'Yosef',     gloss:'Joseph (= Tzion)',    value:156 },
  { lang:'hebrew', word:'שמים', translit:'shamayim',  gloss:'heavens',             value:390 },
  { lang:'hebrew', word:'ארץ',  translit:'eretz',     gloss:'earth · land',        value:291 },
  { lang:'hebrew', word:'אדם',  translit:'Adam',      gloss:'man · Adam',          value:45 },
  { lang:'hebrew', word:'מה',   translit:'mah',       gloss:'what (= Adam)',       value:45 },
  { lang:'hebrew', word:'חוה',  translit:'Chava',     gloss:'Eve',                 value:19 },
  { lang:'hebrew', word:'אם',   translit:'em',        gloss:'mother',              value:41 },
  { lang:'hebrew', word:'אב',   translit:'av',        gloss:'father',              value:3 },
  { lang:'hebrew', word:'בן',   translit:'ben',       gloss:'son',                 value:52 },
  { lang:'hebrew', word:'בת',   translit:'bat',       gloss:'daughter',            value:402 },
  { lang:'hebrew', word:'שבת',  translit:'Shabbat',   gloss:'sabbath',             value:702 },
  { lang:'hebrew', word:'אש',   translit:'esh',       gloss:'fire',                value:301 },
  { lang:'hebrew', word:'מים',  translit:'mayim',     gloss:'water',               value:90 },
  { lang:'hebrew', word:'שמש',  translit:'shemesh',   gloss:'sun',                 value:640 },
  { lang:'hebrew', word:'ירח',  translit:'yarach',    gloss:'moon',                value:218 },
  { lang:'hebrew', word:'אמת',  translit:'emet',      gloss:'truth',               value:441 },
  { lang:'hebrew', word:'אברהם',translit:'Avraham',   gloss:'Abraham',             value:248 },
  { lang:'hebrew', word:'רחם',  translit:'rachem',    gloss:'mercy · womb',        value:248 },
  { lang:'hebrew', word:'משה',  translit:'Moshe',     gloss:'Moses',               value:345 },
  { lang:'hebrew', word:'השם',  translit:'HaShem',    gloss:'The Name',            value:345 },
  { lang:'hebrew', word:'יעקב', translit:'Yaakov',    gloss:'Jacob',               value:182 },
  { lang:'hebrew', word:'ברוך', translit:'baruch',    gloss:'blessed',             value:228 },
  { lang:'hebrew', word:'עולם', translit:'olam',      gloss:'world · eternity',    value:146 },
  { lang:'hebrew', word:'נר',   translit:'ner',       gloss:'candle · lamp',       value:250 },
  { lang:'hebrew', word:'צדיק', translit:'tzaddik',   gloss:'righteous one',       value:204 },
  { lang:'hebrew', word:'יין',  translit:'yayin',     gloss:'wine (= sod)',        value:70 },
  { lang:'hebrew', word:'סוד',  translit:'sod',       gloss:'secret',              value:70 },

  /* ---------- GREEK ---------- */
  { lang:'greek', word:'λογος',     translit:'logos',    gloss:'word · reason',     value:373 },
  { lang:'greek', word:'αγαπη',     translit:'agapē',    gloss:'love',              value:93 },
  { lang:'greek', word:'σοφια',     translit:'sophia',   gloss:'wisdom',            value:781 },
  { lang:'greek', word:'αληθεια',   translit:'alētheia', gloss:'truth',             value:64 },
  { lang:'greek', word:'πιστις',    translit:'pistis',   gloss:'faith',             value:800 },
  { lang:'greek', word:'κυριος',    translit:'kurios',   gloss:'lord',              value:800 },
  { lang:'greek', word:'ελπις',     translit:'elpis',    gloss:'hope',              value:325 },
  { lang:'greek', word:'ιησους',    translit:'Iēsous',   gloss:'Jesus',             value:888 },
  { lang:'greek', word:'χριστος',   translit:'Christos', gloss:'Christ',            value:1480 },
  { lang:'greek', word:'θεος',      translit:'theos',    gloss:'god',               value:284 },
  { lang:'greek', word:'αμην',      translit:'amēn',     gloss:'amen',              value:99 },
  { lang:'greek', word:'ζωη',       translit:'zōē',      gloss:'life',              value:815 },
  { lang:'greek', word:'φως',       translit:'phōs',     gloss:'light',             value:1500 },
  { lang:'greek', word:'αγγελος',   translit:'angelos',  gloss:'angel · messenger', value:312 },
  { lang:'greek', word:'ψυχη',      translit:'psychē',   gloss:'soul',              value:1708 },
  { lang:'greek', word:'σωμα',      translit:'sōma',     gloss:'body',              value:1041 },
  { lang:'greek', word:'κοσμος',    translit:'kosmos',   gloss:'world · order',     value:600 },
  { lang:'greek', word:'αρχη',      translit:'archē',    gloss:'beginning',         value:709 },
  { lang:'greek', word:'τελος',     translit:'telos',    gloss:'end · purpose',     value:605 },
  { lang:'greek', word:'πατηρ',     translit:'patēr',    gloss:'father',            value:489 },
  { lang:'greek', word:'μητηρ',     translit:'mētēr',    gloss:'mother',            value:456 },
  { lang:'greek', word:'υιος',      translit:'huios',    gloss:'son',               value:680 },
  { lang:'greek', word:'πνευμα',    translit:'pneuma',   gloss:'spirit · breath',   value:576 },
  { lang:'greek', word:'πυρ',       translit:'pyr',      gloss:'fire',              value:580 },
  { lang:'greek', word:'γη',        translit:'gē',       gloss:'earth',             value:11 },
  { lang:'greek', word:'τειταν',    translit:'teitan',   gloss:'Titan (= 666)',     value:666 },
  { lang:'greek', word:'αδαμ',      translit:'Adam',     gloss:'Adam',              value:46 },
  { lang:'greek', word:'ευαγγελιον',translit:'evangelion',gloss:'good news',        value:577 },
  { lang:'greek', word:'σωτηρ',     translit:'sōtēr',    gloss:'saviour',           value:1408 },
  { lang:'greek', word:'βασιλευς',  translit:'basileus', gloss:'king',              value:848 },
  { lang:'greek', word:'αλφα',      translit:'alpha',    gloss:'alpha',             value:532 },
  { lang:'greek', word:'ωμεγα',     translit:'ōmega',    gloss:'omega',             value:849 },
  { lang:'greek', word:'ειρηνη',    translit:'eirēnē',   gloss:'peace',             value:181 },
  { lang:'greek', word:'γνωσις',    translit:'gnōsis',   gloss:'knowledge',         value:1263 },
  { lang:'greek', word:'νους',      translit:'nous',     gloss:'mind',              value:720 },

  /* ---------- ARABIC ---------- */
  { lang:'arabic', word:'الله',      translit:'Allāh',     gloss:'God',                  value:66 },
  { lang:'arabic', word:'محمد',      translit:'Muḥammad',  gloss:'the Prophet',          value:92 },
  { lang:'arabic', word:'علي',       translit:'ʿAlī',      gloss:'ʿAli',                 value:110 },
  { lang:'arabic', word:'نور',       translit:'nūr',       gloss:'light',                value:256 },
  { lang:'arabic', word:'حق',        translit:'ḥaqq',      gloss:'truth · the Real',     value:108 },
  { lang:'arabic', word:'حب',        translit:'ḥubb',      gloss:'love',                 value:10 },
  { lang:'arabic', word:'علم',       translit:'ʿilm',      gloss:'knowledge',            value:140 },
  { lang:'arabic', word:'عقل',       translit:'ʿaql',      gloss:'intellect',            value:200 },
  { lang:'arabic', word:'روح',       translit:'rūḥ',       gloss:'spirit',               value:214 },
  { lang:'arabic', word:'قلب',       translit:'qalb',      gloss:'heart',                value:132 },
  { lang:'arabic', word:'نفس',       translit:'nafs',      gloss:'soul · self',          value:190 },
  { lang:'arabic', word:'إيمان',     translit:'īmān',      gloss:'faith',                value:102 },
  { lang:'arabic', word:'إسلام',     translit:'islām',     gloss:'submission',           value:132 },
  { lang:'arabic', word:'صلاة',      translit:'ṣalāt',     gloss:'prayer',               value:126 },
  { lang:'arabic', word:'القرآن',    translit:'al-Qurʾān', gloss:'the Qur’an',           value:382 },
  { lang:'arabic', word:'كتاب',      translit:'kitāb',     gloss:'book',                 value:423 },
  { lang:'arabic', word:'جنة',       translit:'janna',     gloss:'garden · paradise',    value:58 },
  { lang:'arabic', word:'نار',       translit:'nār',       gloss:'fire',                 value:251 },
  { lang:'arabic', word:'ماء',       translit:'māʾ',       gloss:'water',                value:42 },
  { lang:'arabic', word:'شمس',       translit:'shams',     gloss:'sun',                  value:400 },
  { lang:'arabic', word:'قمر',       translit:'qamar',     gloss:'moon',                 value:340 },
  { lang:'arabic', word:'يوم',       translit:'yawm',      gloss:'day',                  value:56 },
  { lang:'arabic', word:'ليل',       translit:'layl',      gloss:'night',                value:70 },
  { lang:'arabic', word:'الرحمن',    translit:'al-Raḥmān', gloss:'the Merciful',         value:329 },
  { lang:'arabic', word:'الرحيم',    translit:'al-Raḥīm',  gloss:'the Compassionate',    value:289 },
  { lang:'arabic', word:'سلام',      translit:'salām',     gloss:'peace',                value:131 },
  { lang:'arabic', word:'بركة',      translit:'baraka',    gloss:'blessing',             value:227 },
  { lang:'arabic', word:'حكمة',      translit:'ḥikma',     gloss:'wisdom',               value:73 },
  { lang:'arabic', word:'صبر',       translit:'ṣabr',      gloss:'patience',             value:292 },
  { lang:'arabic', word:'شكر',       translit:'shukr',     gloss:'gratitude',            value:520 },

  /* ---------- ENGLISH ---------- */
  { lang:'english', word:'GOD',     translit:'',  gloss:'God',                value:26 },
  { lang:'english', word:'LOVE',    translit:'',  gloss:'love',               value:54 },
  { lang:'english', word:'SUN',     translit:'',  gloss:'sun (= love)',       value:54 },
  { lang:'english', word:'LIGHT',   translit:'',  gloss:'light',              value:56 },
  { lang:'english', word:'HUMAN',   translit:'',  gloss:'human (= light)',    value:56 },
  { lang:'english', word:'TRUTH',   translit:'',  gloss:'truth',              value:87 },
  { lang:'english', word:'PEACE',   translit:'',  gloss:'peace',              value:30 },
  { lang:'english', word:'WISDOM',  translit:'',  gloss:'wisdom',             value:83 },
  { lang:'english', word:'LIFE',    translit:'',  gloss:'life',               value:32 },
  { lang:'english', word:'HEART',   translit:'',  gloss:'heart',              value:52 },
  { lang:'english', word:'EARTH',   translit:'',  gloss:'earth (= heart)',    value:52 },
  { lang:'english', word:'SOUL',    translit:'',  gloss:'soul',               value:67 },
  { lang:'english', word:'WATER',   translit:'',  gloss:'water (= soul)',     value:67 },
  { lang:'english', word:'CROSS',   translit:'',  gloss:'cross (= soul)',     value:67 },
  { lang:'english', word:'SPIRIT',  translit:'',  gloss:'spirit',             value:91 },
  { lang:'english', word:'HOPE',    translit:'',  gloss:'hope',               value:44 },
  { lang:'english', word:'FAITH',   translit:'',  gloss:'faith (= hope)',     value:44 },
  { lang:'english', word:'DREAM',   translit:'',  gloss:'dream',              value:41 },
  { lang:'english', word:'KING',    translit:'',  gloss:'king (= dream)',     value:41 },
  { lang:'english', word:'ANGEL',   translit:'',  gloss:'angel',              value:39 },
  { lang:'english', word:'HEAVEN',  translit:'',  gloss:'heaven',             value:55 },
  { lang:'english', word:'DIVINE',  translit:'',  gloss:'divine',             value:63 },
  { lang:'english', word:'ETERNAL', translit:'',  gloss:'eternal',            value:75 },
  { lang:'english', word:'INFINITY',translit:'',  gloss:'infinity',           value:106 },
  { lang:'english', word:'COSMOS',  translit:'',  gloss:'cosmos',             value:84 },
  { lang:'english', word:'STAR',    translit:'',  gloss:'star',               value:58 },
  { lang:'english', word:'FATHER',  translit:'',  gloss:'father (= star)',    value:58 },
  { lang:'english', word:'MOON',    translit:'',  gloss:'moon',               value:57 },
  { lang:'english', word:'FIRE',    translit:'',  gloss:'fire',               value:38 },
  { lang:'english', word:'AIR',     translit:'',  gloss:'air',                value:28 },
  { lang:'english', word:'NAME',    translit:'',  gloss:'name',               value:33 },
  { lang:'english', word:'WORD',    translit:'',  gloss:'word',               value:60 },
  { lang:'english', word:'NUMBER',  translit:'',  gloss:'number',             value:73 },
  { lang:'english', word:'MOTHER',  translit:'',  gloss:'mother',             value:79 },
  { lang:'english', word:'CHILD',   translit:'',  gloss:'child',              value:36 },
  { lang:'english', word:'TEMPLE',  translit:'',  gloss:'temple',             value:71 },
];

export const EQUIV_SYSTEM = {
  english: 'English Ordinal',
  hebrew:  'Mispar Hechrechi',
  greek:   'Isopsephy',
  arabic:  'Abjad Hawwaz',
};

export function findEquivalents(lang, value, omitWord) {
  if (!value) return [];
  return EQUIVALENT_CORPUS.filter(e =>
    e.lang === lang && e.value === value && (!omitWord || e.word !== omitWord)
  );
}
