// Gematria — letter symbolism + correspondences. Ported verbatim.
// Used by the letter modal in the Word mode.

export const LETTER_LORE = {
  hebrew: {
    'א':{ name:'Aleph',  symbol:'Ox · Leader · Divine breath', correspondence:'Air · The Fool · Keter',
          body:'The silent supreme letter — the breath that holds every sound without being any of them. Pictogram of an ox-head: primacy, the force that pulls the plough of creation. The first letter, the One that contains all.' },
    'ב':{ name:'Bet',    symbol:'House · Dwelling · Container', correspondence:'Mercury · The Magician · Chochmah',
          body:'The first letter of Torah (בְּרֵאשִׁית). The house, the indwelling, the womb of creation. Duality of inside and outside. The dot within marks the divine spark hidden in form.' },
    'ג':{ name:'Gimel',  symbol:'Camel · Bridge · The giver',   correspondence:'Moon · The High Priestess · Binah',
          body:'The camel that bears treasure across the desert. The lifter-up, the bridge of charity (gemilut chasadim) between rich and poor, heaven and earth.' },
    'ד':{ name:'Dalet',  symbol:'Door · Threshold · The poor',  correspondence:'Venus · The Empress · Chesed',
          body:'The doorway, the humble one who opens to receive. The poor who has nothing of his own — and so receives all. Threshold between worlds.' },
    'ה':{ name:'Hey',    symbol:'Window · Breath · Revelation', correspondence:'Aries · The Emperor · Gevurah',
          body:'The window through which divine breath enters. The letter doubled in YHVH; manifestation, presence, the soft exhale that creates the world.' },
    'ו':{ name:'Vav',    symbol:'Hook · Nail · Connector',      correspondence:'Taurus · The Hierophant · Tiferet',
          body:'The hook that joins, the nail that fastens. The conjunction "and" in Hebrew. The pillar that connects heaven and earth, the sixth day of creation.' },
    'ז':{ name:'Zayin',  symbol:'Sword · Weapon · Mastery',     correspondence:'Gemini · The Lovers · Netzach',
          body:'The sword of discrimination, the seventh-day rest that severs from work. Mastery, dominion, the cutting that creates form.' },
    'ח':{ name:'Het',    symbol:'Fence · Hedge · Life',         correspondence:'Cancer · The Chariot · Hod',
          body:'The fence that protects life (chai, חי = 18). What separates and so makes form possible. The boundary that holds the sacred.' },
    'ט':{ name:'Tet',    symbol:'Coiled serpent · Hidden good', correspondence:'Leo · Strength · Yesod',
          body:'The serpent coiled, the hidden good (טוב). The womb in which goodness gestates before being seen.' },
    'י':{ name:'Yod',    symbol:'Hand · Point · Seed',          correspondence:'Virgo · The Hermit · Malkuth',
          body:'The smallest letter, the seed of all letters. The hand of God, the originating point. From the yod, every other letter is born.' },
    'כ':{ name:'Kaf',    symbol:'Open palm · Cup · Crown',      correspondence:'Jupiter · Wheel of Fortune',
          body:'The open palm, the bowl that receives divine influx. Potential, capacity. The crown as a hollow ready to be filled.' },
    'ך':{ name:'Kaf sofit', symbol:'Final Kaf · Sealed palm',   correspondence:'Final form · 500',
          body:'The closed palm at the end of a word. Carries the Mispar Gadol value of 500. The sealed receiving — what has been given, contained.' },
    'ל':{ name:'Lamed',  symbol:'Ox-goad · Teacher · Heart',    correspondence:'Libra · Justice',
          body:'The tallest letter, ascending toward heaven. The ox-goad that urges, the teacher who learns through teaching. The heart of the alphabet.' },
    'מ':{ name:'Mem',    symbol:'Water · Womb · Wisdom',        correspondence:'Water · The Hanged Man',
          body:'The waters above and below. Open Mem (מ) for revealed wisdom; closed Mem (ם) for hidden wisdom.' },
    'ם':{ name:'Mem sofit', symbol:'Final Mem · Sealed water',  correspondence:'Final form · 600',
          body:'The closed Mem, the hidden waters. Mispar Gadol value 600. The mystery preserved at the end of the word.' },
    'נ':{ name:'Nun',    symbol:'Fish · Soul · Faithful',       correspondence:'Scorpio · Death',
          body:'The fish swimming in hidden waters of consciousness. Faithfulness (ne’eman). The soul that descends and ascends.' },
    'ן':{ name:'Nun sofit', symbol:'Final Nun · Soul descending', correspondence:'Final form · 700',
          body:'The Nun extending below the line. Mispar Gadol value 700. The soul reaching downward; faithfulness sealed.' },
    'ס':{ name:'Samekh', symbol:'Support · Closed circle · Trust', correspondence:'Sagittarius · Temperance',
          body:'The supporter (samakh = to lean on). The closed circle — divine providence that holds when nothing else can.' },
    'ע':{ name:'Ayin',   symbol:'Eye · Fountain · Source',      correspondence:'Capricorn · The Devil',
          body:'The eye through which seeing flows. Also a fountain, a source. Perception turned inward becomes the well of meaning.' },
    'פ':{ name:'Pe',     symbol:'Mouth · Speech · Word',        correspondence:'Mars · The Tower',
          body:'The mouth, the divine word. Breath becoming form. The tooth (Shin) is hidden inside the mouth (Pe).' },
    'ף':{ name:'Pe sofit', symbol:'Final Pe · Mouth sealed',    correspondence:'Final form · 800',
          body:'The closed mouth. Mispar Gadol value 800. The word made silent, contained, finished.' },
    'צ':{ name:'Tsade',  symbol:'Fishhook · Righteous · Hunter', correspondence:'Aquarius · The Star',
          body:'The fishhook that draws wisdom from depth. The righteous one (tsadik) who hunts for truth among many waters.' },
    'ץ':{ name:'Tsade sofit', symbol:'Final Tsade · Hook descending', correspondence:'Final form · 900',
          body:'The Tsade extending below — the righteous reaching down. Mispar Gadol value 900.' },
    'ק':{ name:'Qof',    symbol:'Back of head · Holiness · Cycle', correspondence:'Pisces · The Moon',
          body:'The only letter that descends below the baseline. Holiness (kadosh) reaching down into the world.' },
    'ר':{ name:'Resh',   symbol:'Head · Beginning · Principle', correspondence:'Sun · The Sun',
          body:'The head, the principle (rosh = beginning). The chief idea, the leading thought.' },
    'ש':{ name:'Shin',   symbol:'Tooth · Fire · Threefold flame', correspondence:'Fire · Judgement / Aeon',
          body:'The threefold flame of divine fire. The teeth that grind and divide. Letter of the divine name Shaddai (שדי).' },
    'ת':{ name:'Tav',    symbol:'Mark · Sign · Cross · Truth',  correspondence:'Saturn · The World',
          body:'The seal, the mark, the final letter. Truth (אמת) ends with Tav. Completion: when a thing has reached its end, it has reached its truth.' },
  },
  greek: {
    'α':{ name:'Alpha',   symbol:'Beginning · The Ox',          correspondence:'Air · First',
          body:'"I am the Alpha and the Omega." The originating sound, the first principle. From Phoenician aleph.' },
    'β':{ name:'Beta',    symbol:'House · Container',           correspondence:'Mercury · Second',
          body:'The dwelling, the structure. The element of containment — the form that holds meaning.' },
    'γ':{ name:'Gamma',   symbol:'Throwstick · Camel · Path',   correspondence:'Movement',
          body:'The angled, throwing motion. Genesis (γένεσις) — origin and becoming.' },
    'δ':{ name:'Delta',   symbol:'Door · Triangle · Change',    correspondence:'Transformation',
          body:'The triangle, the river-mouth, the door of change. Mathematical symbol for difference itself.' },
    'ε':{ name:'Epsilon', symbol:'Window · Breath',             correspondence:'Short E · Voice',
          body:'The short e, the breath of speech. Carved at Delphi: the famous "E" whose meaning Plutarch puzzled over.' },
    'ϛ':{ name:'Stigma · Digamma', symbol:'The lost letter · 6', correspondence:'Hidden number',
          body:'The vanished sixth letter. Once a sound (w) the Greeks lost; survived only as the number six.' },
    'ζ':{ name:'Zeta',    symbol:'Sword · Cut',                 correspondence:'Distinction',
          body:'The cutting letter. Zōē (ζωή = life) — life as that which distinguishes itself from non-life.' },
    'η':{ name:'Eta',     symbol:'Fence · Long E',              correspondence:'Boundary',
          body:'The long e. Originally the rough breathing (h-sound) before becoming a vowel.' },
    'θ':{ name:'Theta',   symbol:'Wheel · Divine',              correspondence:'God · Death',
          body:'Theos (θεός = god), thanatos (θάνατος = death). The wheel of the great mysteries.' },
    'ι':{ name:'Iota',    symbol:'Hand · Point · Smallest',     correspondence:'The seed',
          body:'"Not one iota" — the smallest possible mark. The seed of every other letter.' },
    'κ':{ name:'Kappa',   symbol:'Palm · Receiving',            correspondence:'Curve',
          body:'The bent line, the holding hand. Kosmos (κόσμος = order) begins here.' },
    'λ':{ name:'Lambda',  symbol:'Goad · Triangle · Light',     correspondence:'Logos',
          body:'The upward-pointing triangle. Logos (λόγος = word, reason) — the principle of order.' },
    'μ':{ name:'Mu',      symbol:'Water · Mother · Matter',     correspondence:'Fluid',
          body:'Mētēr (μήτηρ = mother), matter (matēr). The fluid origin from which all takes shape.' },
    'ν':{ name:'Nu',      symbol:'Fish · Mind',                 correspondence:'Intellect',
          body:'Nous (νοῦς = mind, intellect). The fish swimming in the waters of consciousness.' },
    'ξ':{ name:'Xi',      symbol:'Support · The stranger',      correspondence:'Foreign',
          body:'Xenos (ξένος = stranger, guest). The unfamiliar that becomes familiar through hospitality.' },
    'ο':{ name:'Omicron', symbol:'Eye · Small O',               correspondence:'The point seen',
          body:'The small o. The eye, the perception, the small circle that contains all perception.' },
    'π':{ name:'Pi',      symbol:'Mouth · Ratio',               correspondence:'The circle’s secret',
          body:'The mouth, the speech. Mathematical π — the irrational number that encodes the circle.' },
    'ϟ':{ name:'Koppa',   symbol:'Archaic Q · 90',              correspondence:'Hidden number',
          body:'The vanished Q-letter, surviving only in numerals as 90.' },
    'ρ':{ name:'Rho',     symbol:'Head · River',                correspondence:'Flow',
          body:'Rheō (ῥέω = to flow). "All things flow" — Heraclitus.' },
    'σ':{ name:'Sigma',   symbol:'Tooth · Wisdom · Sum',        correspondence:'Knowing',
          body:'Sophia (σοφία = wisdom). Mathematical Σ — the sum of all parts.' },
    'τ':{ name:'Tau',     symbol:'Cross · Mark · Seal',         correspondence:'Completion',
          body:'The cross-mark, the seal. The Christian cross was originally the tau.' },
    'υ':{ name:'Upsilon', symbol:'Y of choice · Two paths',     correspondence:'Decision',
          body:'The Pythagorean letter — the Y where the path of virtue and vice diverge.' },
    'φ':{ name:'Phi',     symbol:'Light · Divine proportion',   correspondence:'Beauty',
          body:'Phōs (φῶς = light), philosophy. The golden ratio φ ≈ 1.618.' },
    'χ':{ name:'Chi',     symbol:'Cross · Christ',              correspondence:'Intersection',
          body:'The X of intersection. The Christ (Χριστός) — the meeting of human and divine.' },
    'ψ':{ name:'Psi',     symbol:'Trident · Soul',              correspondence:'Breath',
          body:'Psychē (ψυχή = soul, breath). The trident — three-pointed.' },
    'ω':{ name:'Omega',   symbol:'Great O · The end',           correspondence:'Completion',
          body:'"I am the Alpha and the Omega." Completion of the cycle, the return to source.' },
    'ϡ':{ name:'Sampi',   symbol:'End-letter · 900',            correspondence:'Final number',
          body:'The numerical end of the Greek alphabet. Sampi closes the circle of values.' },
  },
  arabic: {
    'ا':{ name:'Alif',    symbol:'The standing one · Unity',    correspondence:'1 · Allah',
          body:'The first letter, the divine unity (waḥdah). The vertical stroke from which all creation descends.' },
    'ب':{ name:'Ba',      symbol:'House · Bismillah · The dot', correspondence:'2 · Doorway',
          body:'The letter beneath which the dot of creation appears. "Bismillah" — in the name of God.' },
    'ت':{ name:'Ta',      symbol:'Repentance · Return',         correspondence:'400 · Turning back',
          body:'Tawba (توبة) — repentance, return. The two dots above mark ascending movement back to source.' },
    'ث':{ name:'Tha',     symbol:'Sublimation · Three',         correspondence:'500 · Refinement',
          body:'Three points of refinement. The triple ascent of the soul through purification.' },
    'ج':{ name:'Jim',     symbol:'Beauty · Gathering',          correspondence:'3 · Assembly',
          body:'Jamāl (جمال) — beauty. The dot held within the curve like a pearl in its shell.' },
    'ح':{ name:'Ha',      symbol:'Life · The living',           correspondence:'8 · Breath',
          body:'Ḥayy (حيّ) — the living one, one of the divine names. The breath of life itself.' },
    'خ':{ name:'Kha',     symbol:'Loss · Heaviness',            correspondence:'600 · Fear',
          body:'Khawf (خوف) — fear, that which weighs the heart. The dot above marking heaviness.' },
    'د':{ name:'Dal',     symbol:'Direction · Evidence',        correspondence:'4 · Pointing',
          body:'Dalīl (دليل) — guide, evidence. The hand pointing the way.' },
    'ذ':{ name:'Dhal',    symbol:'Possessor',                   correspondence:'700 · Owning',
          body:'Dhū (ذو) — the one who has, the possessor. Dhikr (ذكر) — remembrance.' },
    'ر':{ name:'Ra',      symbol:'Lord · Mercy',                correspondence:'200 · Lordship',
          body:'Rabb (ربّ) — Lord. Raḥma (رحمة) — mercy. The lordship that nurtures and sustains.' },
    'ز':{ name:'Zay',     symbol:'Vibration · Ornament',        correspondence:'7 · Adornment',
          body:'Zīna (زينة) — adornment. The vibration of beauty.' },
    'س':{ name:'Sin',     symbol:'Light · Secret',              correspondence:'60 · Hidden',
          body:'Sirr (سرّ) — secret, the inmost station of the heart.' },
    'ش':{ name:'Shin',    symbol:'Witnessing',                  correspondence:'300 · Testimony',
          body:'Shahāda (شهادة) — bearing witness to divine unity.' },
    'ص':{ name:'Sad',     symbol:'Truthfulness · Patience',     correspondence:'90 · Sincerity',
          body:'Ṣidq (صدق) — truthfulness; ṣabr (صبر) — patience. The pure heart that does not bend.' },
    'ض':{ name:'Dad',     symbol:'The unique letter · Necessity', correspondence:'800 · Proof',
          body:'The letter unique to Arabic — Arabic is called lughat al-ḍād, "the language of the ḍād."' },
    'ط':{ name:'Ta',      symbol:'Goodness · Purity',           correspondence:'9 · Cleansing',
          body:'Ṭāhir (طاهر) — pure. Ṭayyib (طيب) — wholesome.' },
    'ظ':{ name:'Za',      symbol:'Manifestation',               correspondence:'900 · Visible',
          body:'Ẓāhir (ظاهر) — the manifest, one of the divine names.' },
    'ع':{ name:'Ayn',     symbol:'Eye · Fountain · Essence',    correspondence:'70 · Source',
          body:'ʿAyn (عين) — eye, fountain, essence. The source from which seeing flows.' },
    'غ':{ name:'Ghayn',   symbol:'The hidden · Cloud',          correspondence:'1000 · Unseen',
          body:'Ghayb (غيب) — the unseen, the realm beyond perception.' },
    'ف':{ name:'Fa',      symbol:'Opening · Victory',           correspondence:'80 · Breakthrough',
          body:'Fatḥ (فتح) — opening, conquest. The opening of the heart.' },
    'ق':{ name:'Qaf',     symbol:'Mountain · Holiness',         correspondence:'100 · Cosmic',
          body:'Mt. Qāf, the mythical mountain that surrounds the world.' },
    'ك':{ name:'Kaf',     symbol:'Sufficient · Be!',            correspondence:'20 · Command',
          body:'Kāfī (كاف) — sufficient. Kun (كن) — "Be!" The divine command of creation.' },
    'ل':{ name:'Lam',     symbol:'Lordship · The double',       correspondence:'30 · Divine name',
          body:'The two lams of the divine name Allāh (الله).' },
    'م':{ name:'Mim',     symbol:'Mercy · Muḥammad',            correspondence:'40 · Compassion',
          body:'The closed circle of completion. Raḥma (رحمة) — mercy.' },
    'ن':{ name:'Nun',     symbol:'Fish · Pen · Divine ink',     correspondence:'50 · The qalam',
          body:'"Nūn. By the pen, and what they inscribe." (Qur’an 68:1)' },
    'ه':{ name:'Ha',      symbol:'Identity · Huwa',             correspondence:'5 · He-ness',
          body:'Huwa (هو) — "He." The divine pronoun, the personhood of the Real.' },
    'و':{ name:'Waw',     symbol:'Connection · Conjunction',    correspondence:'6 · Union',
          body:'The "and" that joins. Waḥda (وحدة) — unity.' },
    'ي':{ name:'Ya',      symbol:'Hand · Calling',              correspondence:'10 · Vocative',
          body:'Yā (يا) — "O!" the calling. The vocative of devotion.' },
  },
  english: {
    'A':{ name:'A',  symbol:'Ox · Origin',           correspondence:'From Aleph · Air',          body:'Descended from the Phoenician aleph, the ox-head. The first sound of speech.' },
    'B':{ name:'B',  symbol:'House · Dwelling',       correspondence:'From Bet · Container',       body:'The two-chambered house. The first consonant.' },
    'C':{ name:'C',  symbol:'Curve · Throwstick',     correspondence:'From Gimel · Movement',      body:'The bent throwing-stick. The curve that opens.' },
    'D':{ name:'D',  symbol:'Door · Threshold',       correspondence:'From Dalet · Opening',       body:'The door, the triangle. Threshold between rooms.' },
    'E':{ name:'E',  symbol:'Window · Breath',        correspondence:'From Hey · Voice',           body:'The window, the breath. The most common vowel in English.' },
    'F':{ name:'F',  symbol:'Hook · Connector',       correspondence:'From Vav · Joining',         body:'The hook, the conjunction.' },
    'G':{ name:'G',  symbol:'Camel · Bridge',         correspondence:'From Gimel',                 body:'A Roman invention to distinguish from C.' },
    'H':{ name:'H',  symbol:'Fence · Hedge',          correspondence:'From Het · Boundary',        body:'The breath, the rough breathing.' },
    'I':{ name:'I',  symbol:'Hand · Point · Self',    correspondence:'From Yod · Seed',            body:'The single stroke. The I of the self.' },
    'J':{ name:'J',  symbol:'Hand below · Descent',   correspondence:'From Yod · Reach',           body:'A late split from I.' },
    'K':{ name:'K',  symbol:'Palm · Receiving',       correspondence:'From Kaf',                   body:'The open hand. The cup that holds.' },
    'L':{ name:'L',  symbol:'Goad · Teacher',         correspondence:'From Lamed',                 body:'The goad, the angle that turns. The teacher’s mark.' },
    'M':{ name:'M',  symbol:'Water · Mother',         correspondence:'From Mem · Matter',          body:'The waves of water.' },
    'N':{ name:'N',  symbol:'Fish · Faithful',        correspondence:'From Nun · Soul',            body:'The fish swimming. The mind, the soul.' },
    'O':{ name:'O',  symbol:'Eye · Circle',           correspondence:'From Ayin · Source',         body:'The eye, the circle. The vowel of wonder.' },
    'P':{ name:'P',  symbol:'Mouth · Speech',         correspondence:'From Pe',                    body:'The mouth, the prophet, the priest.' },
    'Q':{ name:'Q',  symbol:'Back of head · Holy',    correspondence:'From Qof',                   body:'The descender. Always followed by U.' },
    'R':{ name:'R',  symbol:'Head · Principle',       correspondence:'From Resh',                  body:'The head, the chief.' },
    'S':{ name:'S',  symbol:'Tooth · Wisdom',         correspondence:'From Shin / Sigma',          body:'The serpent, the tooth, the sum.' },
    'T':{ name:'T',  symbol:'Cross · Mark',           correspondence:'From Tav · Seal',            body:'The mark, the cross. The seal of completion.' },
    'U':{ name:'U',  symbol:'Cup · Vessel',           correspondence:'From Vav',                   body:'The open cup, the vessel.' },
    'V':{ name:'V',  symbol:'Hook · Wedge',           correspondence:'From Vav',                   body:'The wedge of joining, the Roman five.' },
    'W':{ name:'W',  symbol:'Double V · Two waters',  correspondence:'From Vav doubled',           body:'A medieval invention. Twin hooks.' },
    'X':{ name:'X',  symbol:'Cross of intersection',  correspondence:'From Chi',                   body:'The Greek chi, the unknown, the crossing.' },
    'Y':{ name:'Y',  symbol:'Y of choice · Two paths',correspondence:'From Upsilon · Pythagorean', body:'The Pythagorean letter of decision.' },
    'Z':{ name:'Z',  symbol:'Sword · Cut',            correspondence:'From Zayin / Zeta',          body:'The cutting letter, the lightning.' },
  },
};

// Variants for Arabic letter forms
LETTER_LORE.arabic['أ'] = LETTER_LORE.arabic['ا'];
LETTER_LORE.arabic['إ'] = LETTER_LORE.arabic['ا'];
LETTER_LORE.arabic['آ'] = LETTER_LORE.arabic['ا'];
LETTER_LORE.arabic['ة'] = LETTER_LORE.arabic['ت'];
LETTER_LORE.arabic['ى'] = LETTER_LORE.arabic['ي'];
LETTER_LORE.arabic['ؤ'] = LETTER_LORE.arabic['و'];
LETTER_LORE.arabic['ئ'] = LETTER_LORE.arabic['ي'];
LETTER_LORE.greek['ς']  = LETTER_LORE.greek['σ'];

export function getLetterLore(letter, lang) {
  if (!LETTER_LORE[lang]) return null;
  if (lang === 'english') return LETTER_LORE.english[letter.toUpperCase()] || null;
  if (lang === 'greek')   return LETTER_LORE.greek[letter] || LETTER_LORE.greek[letter.toLowerCase()] || null;
  return LETTER_LORE[lang][letter] || null;
}
