import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';
import '../shared/design/tokens.css';
import '../index.css';
import { initSwiss } from '../astro/ephemeris.js';
import { swissBrowserInit } from '../astro/swissBrowserInit.js';
import { migrateLegacyToShared } from '../shared/lib/sharedBirth.js';

// Lift any legacy v1 birth/profiles into the shared mirror once.
migrateLegacyToShared();

// Kick off Swiss WASM init in the background — first paint must NOT block on
// the 12 MB ephemeris download. Components gate on isSwissReady() (or the
// onSwissStateChange subscription) so they re-render once the precise
// backend is online. On failure the Standish+Meeus fallback stays active.
initSwiss({ browserInit: swissBrowserInit });

// Register the Service Worker generated by vite-plugin-pwa (production
// build only). The SW precaches the app shell + earth textures and
// runtime-caches the 12 MB Swiss data blob on first fetch so subsequent
// visits work offline. `virtual:pwa-register` is a virtual module provided
// by the plugin; guarded so dev / Node contexts don't fail.
if (typeof window !== 'undefined' && 'serviceWorker' in navigator) {
  import('virtual:pwa-register')
    .then(({ registerSW }) => registerSW({ immediate: true }))
    .catch(() => { /* dev build or plugin disabled — no SW */ });
}

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
